### ISSUE TITLE
RunTimeError during analysis of hls .ts chunk

### ISSUE THREAD

**Issue by msmithng** [WMSPanel/mpeg2ts#2]
../mpeg2ts.rb:207:in `processAdaptationField': not supported adaptation field (RuntimeError)
	from /Users/msmith/bgrepo/git/mpeg2ts/mpeg2ts.rb:418:in `processMPEG2TSBlock'
	from /Users/msmith/bgrepo/git/mpeg2ts/mpeg2ts.rb:450:in `block in <main>'
	from /Users/msmith/bgrepo/git/mpeg2ts/mpeg2ts.rb:443:in `open'
	from /Users/msmith/bgrepo/git/mpeg2ts/mpeg2ts.rb:443:in `<main>'

I'm running on OSX 10.9.5 and trying to analyze a .ts file from an instance of wowza 4.1.x.

$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]

**Comment by WMSPanel** [comment]
Hi,

Thanks for the feedback. So as I understand, it gives error but keeps working and actually performs the analysis, is that what you mean?

Thank you.

**Comment by msmithng** [comment]
No, it appears to fail after it scrapes the initial container metadata.

$ ruby ~/mpeg2ts.rb media_w1762149747_140113.ts
"Elementary Stream Description {"
" PID=258"
" TYPE=21"
" TYPE_DESC=Metadata carried in PES packets"
" DESC=[38, 13, 255, 255, 73, 68, 51, 32, 255, 73, 68, 51, 32, 0, 15]"
"}"
"Elementary Stream Description {"
" PID=256"
" TYPE=27"
" TYPE_DESC=AVC video stream as defined in ITU-T Rec. H.264 | ISO/IEC 14496-10 Video"
"}"
"Elementary Stream Description {"
" PID=257"
" TYPE=15"
" TYPE_DESC=ISO/IEC 13818-7 Audio with ADTS transport syntax"
"}"
/mpeg2ts.rb:207:in `processAdaptationField': not supported adaptation field (RuntimeError)
	from /mpeg2ts.rb:418:in `processMPEG2TSBlock'
	from /mpeg2ts.rb:450:in `block in <main>'
	from /mpeg2ts.rb:443:in `open'
	from /mpeg2ts.rb:443:in `<main>'

**Comment by WMSPanel** [comment]
Got it. Can you also send media_w1762149747_140113.ts or similar file so we could reproduce the issue?

**Comment by msmithng** [comment]
Sure.

**Comment by msmithng** [comment]
If you need the playlist as well, I can provide that. In the interim, here is the .ts chunk.



Michael

**Comment by WMSPanel** [comment]
I'm sorry, I don't see chunks attached to this ticket.

**Comment by msmithng** [comment]
My apologies... I guess the attachment didn't work last time. Since gh doesn't allow uploading zip files, I've dumped a set of chunks onto dropbox. The *_ao.m3u8 and related files are supposedly audio only. For this conversation, I wouldn't worry about those as I'm only trying to test the playlist.m3u8 at the moment.

https://www.dropbox.com/s/npepkg3cw07mqgp/feed01.zip?dl=0
